spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: config-service
          uri: lb://config-server
          predicates:
            - Path=/config/**
        - id: eureka-service
          uri: lb://eureka-server
          predicates:
            - Path=/eureka/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
